PREFIX st: <http://www.stackdata.com/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>  

SELECT ?question
	WHERE {
		{ ?question st:isTaggedWith	?tag 			.}
		{ ?question st:createdDate	?createdDate	.}
		{ ?question st:hasOwner		?owner 			.}
		{ ?owner 	st:location		?country 		.}
		FILTER (?createdDate >= ?fromDate &&
			    ?createdDate <= ?toDate).
		
	}